config/routes.rb
Rails.application.routes.draw do
  resource :kittens

  delete '/' => 'kittens#delete', :as => :delete
  patch '/edit' => 'kittens#update', :as => :update
  post '/edit' => 'kittens#edit', :as => :edit
  get '/:id' => 'kittens#show'

  root 'kittens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kitten = Kitten.all

    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html { render "kittens/index" }
      format.json { render :json => @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      flash[:success] = 'Thank you for register your kitten!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @kitten = Kitten.find(params[:id]) || nil

    if @kitten == nil
      redirect_to root_path
    end
  end

  def update
    @kitten = Kitten.find(params[:kitten][:id]) || nil
    if @kitten == nil
      render 'new'
    else
      flash[:edit] = "Thank you for maintain this website updated!"
      @kitten.update(kitten_params)
      redirect_to root_path
    end
  end

  def delete
    @kitten = Kitten.find(params[:kitten_id]) || nil
    if @kitten != nil
      @kitten.delete
    end
    redirect_to root_path
  end

  private
  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten.html.erb
<b><%= kitten.name %></b><br>
Age: <%= kitten.age%><br>
Cuteness: <%= kitten.cuteness%><br>
Softness: <%= kitten.softness%><br>
<%= link_to "Edit this kitten!", edit_path(:id => kitten.id), :method => :post%>
<%= link_to "Delete this kitten!", delete_path(:kitten_id => kitten.id), :confirm => 'Are you sure?', :method => :delete %>
<hr>

app/views/kittens/edit.html.erb
<%= form_for @kitten, url: update_path do |a| %>
  <%= a.text_field :id , style: 'display:none'%>
  Name: <%= a.text_field :name %><br>
  Age: <%= a.text_field :age %><br>
  Cuteness: <%= a.text_field :cuteness %><br>
  Softness: <%= a.text_field :softness %><br>
  <%= a.submit "Edit kitten!" %>
<% end %>

app/views/kittens/index.html.erb
<h1>Kittens#index</h1>
<% if flash[:success] %>
  <div class="success"><%= flash[:success] %></div>
<% end %>
<% if flash[:edit] %>
  <div class="edit"><%= flash[:edit] %></div>
<% end %>
<%= link_to 'Create kittens', new_kittens_path %><br>
<hr>
<%= render @kitten %>

app/views/kittens/new.html.erb
<%= form_for @kitten do |a| %>
  Name:
  <%= a.text_field :name %> <br>
  Age: 
  <%= a.text_field :age %><br>
  Cuteness:
  <%= a.text_field :cuteness %><br>
  Softness:
  <%= a.text_field :softness %><br>
  <%= a.submit "Register kitten!" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleAPI</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>